#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧪 Executando testes com banco separado..."
npm run test:db

echo "🔍 Executando lint-staged..."
npx lint-staged

echo "✅ Pre-commit concluído com sucesso!"
